baseURL = 'https://mlowlevl.xyz/'
languageCode = 'en-us'
title = 'mlowlevl'
theme = 'mlowlevl'

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = 'monokai'
    noClasses = true

disableKinds = ["taxonomy", "term"]

[pagination]
  pagerSize = 6

[params]
  description = "Security research, CTF writeups and blog posts on pwn, malware analysis and osint."
  tagline = "ctf / pwn / malware-analysis"
  github = "https://github.com/ml0w6c65766c"
  threads = "https://www.threads.net/@mlowlevl"
  giscusRepo       = "ml0w6c65766c/blog_comments"
  giscusRepoId     = "R_kgDOSfPezw"
  giscusCategory   = "General"
  giscusCategoryId = "DIC_kwDOSfPez84C9L2H"
