baseURL = 'https://pr1mem.xyz/'
languageCode = 'en-us'
title = 'pr1meM'
theme = 'pr1meM'

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = 'dracula'
    noClasses = true

disableKinds = ["taxonomy", "term"]

[pagination]
  pagerSize = 6

[params]
  description = "Security research, CTF writeups and blog posts on pwn, malware analysis and osint."
  tagline = "ctf / pwn / rev"
  github = "https://github.com/pr1meM"
  threads = "https://www.threads.net/@Pr1meM"
  giscusRepo       = "pr1meM/blog_comments"
  giscusRepoId     = "R_kgDOSfPezw"
  giscusCategory   = "General"
  giscusCategoryId = "DIC_kwDOSfPez84C9L2H"
